In [1]:
%%bash
module list

Currently Loaded Modulefiles:
 1) texlive/2019   2) anaconda/3_5.3.1   3) gromacs2020/2020.0(default)  


In [2]:
%matplotlib inline

In [3]:
import os
import asyncio
import matplotlib.pyplot as plt
import numpy as np
import MDAnalysis as mda

In [4]:
import aimmd
import aimmd.distributed as aimmdd

# GMX engine

In [5]:
n_engines = 4

In [6]:
scratch_dir = "/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/"
#scratch_dir = "/home/think/scratch/aimmd_distributed/"
wdirs = [os.path.join(scratch_dir, f"engine_wdir{i}") for i in range(n_engines)]

In [7]:
for d in wdirs:
    if not os.path.isdir(d):
        os.mkdir(d)

## `GmxEngine` is a thin wrapper around gromacs
- it has a `prepare()` method (which will call `grompp`) and multiple methods to then rujn the simulation, namely `run()`, `run_walltime()` and `run_nsteps()`

In [8]:
engines = [aimmdd.GmxEngine(gro_file=os.path.join(scratch_dir, "gmx_infiles/conf.gro"),
                            top_file=os.path.join(scratch_dir, "gmx_infiles/topol.top"),
                            ndx_file=None,
                            #mdrun_extra_args="-nt 2",  # use this if your version of GMX is compiled with thread-MPI support
                            mdrun_extra_args="-ntomp 2",  # use this for GMX without thread-MPI support
                            )
           for _ in range(n_engines)]

In [9]:
mdps = [aimmdd.MDP(os.path.join(scratch_dir, "gmx_infiles/md.mdp"))
        for _ in range(n_engines)]

In [10]:
mdps[0].changed

False

In [11]:
mdps[0]

{'title': ['test'], 'cpp': ['/lib/cpp'], 'include': ['-I../top'], 'define': [], 'integrator': ['md-vv'], 'dt': 0.002, 'nsteps': -1, 'nstxout': 10, 'nstvout': 10, 'nstlog': 10, 'nstenergy': 10, 'nstxout-compressed': 10, 'compressed-x-grps': ['Protein'], 'energygrps': ['Protein', 'SOL'], 'nstlist': 10, 'ns-type': ['grid'], 'cutoff-scheme': ['Verlet'], 'rlist': 1.1, 'coulombtype': ['PME'], 'rcoulomb': 1.1, 'rvdw': 1.1, 'tcoupl': ['Berendsen'], 'tc-grps': ['Protein', 'SOL'], 'tau-t': [0.1, 0.1], 'ref-t': [300.0, 300.0], 'Pcoupl': ['Berendsen'], 'tau-p': 1.0, 'compressibility': [4.5e-05], 'ref-p': [1.0], 'gen-vel': ['no'], 'gen-temp': 300.0, 'gen-seed': 173529, 'constraints': ['all-bonds']}

In [12]:
nsteps = 10
for mdp in mdps:
    mdp['nstvout'] = 10
    mdp["nstxout"] = 10

In [13]:
mdps[0]

{'title': ['test'], 'cpp': ['/lib/cpp'], 'include': ['-I../top'], 'define': [], 'integrator': ['md-vv'], 'dt': 0.002, 'nsteps': -1, 'nstxout': 10, 'nstvout': 10, 'nstlog': 10, 'nstenergy': 10, 'nstxout-compressed': 10, 'compressed-x-grps': ['Protein'], 'energygrps': ['Protein', 'SOL'], 'nstlist': 10, 'ns-type': ['grid'], 'cutoff-scheme': ['Verlet'], 'rlist': 1.1, 'coulombtype': ['PME'], 'rcoulomb': 1.1, 'rvdw': 1.1, 'tcoupl': ['Berendsen'], 'tc-grps': ['Protein', 'SOL'], 'tau-t': [0.1, 0.1], 'ref-t': [300.0, 300.0], 'Pcoupl': ['Berendsen'], 'tau-p': 1.0, 'compressibility': [4.5e-05], 'ref-p': [1.0], 'gen-vel': ['no'], 'gen-temp': 300.0, 'gen-seed': 173529, 'constraints': ['all-bonds']}

In [14]:
mdps[0].changed

True

In [15]:
import time

In [16]:
from state_funcs import descriptor_func

descriptor_func_wrap = aimmdd.TrajectoryFunctionWrapper(descriptor_func, {"scratch_dir": scratch_dir})

In [17]:
init_conf = aimmdd.Trajectory(trajectory_file=os.path.join(scratch_dir, "gmx_infiles/conf.gro"),
                              structure_file=os.path.join(scratch_dir, "gmx_infiles/conf.gro"),
                             )

In [18]:
cv = await descriptor_func_wrap(init_conf)
print(cv)

[[-0.18253787 -1.3940568 ]]


In [19]:
start = time.time()
await asyncio.gather(*(e.prepare(starting_configuration=None, workdir=wdir, deffnm="blib", run_config=mdp)
                               for e, wdir, mdp in zip(engines, wdirs, mdps)
                               )
                            )
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 0.22010278701782227 s


In [20]:
walltime = 0.01 # 0.01 h = 36 s
start = time.time()
trajs = await asyncio.gather(*(e.run_walltime(walltime) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 36.62216305732727 s


/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


In [21]:
cv = await descriptor_func_wrap(trajs[0])

In [22]:
cv

array([[-0.1878258 , -1.3769007 ],
       [-0.17010452, -1.4815865 ],
       [-0.18294656, -1.5012429 ],
       ...,
       [ 2.8240066 , -2.2837443 ],
       [ 2.7247763 , -1.9952395 ],
       [ 2.4271595 , -2.2134595 ]], dtype=float32)

In [23]:
for i, e in enumerate(engines):
    print(f"engine {i} did {e.frames_done} frames (== {e.steps_done} integration steps)")

engine 0 did 4641 frames (== 46410 integration steps)
engine 1 did 4681 frames (== 46810 integration steps)
engine 2 did 4657 frames (== 46570 integration steps)
engine 3 did 4665 frames (== 46650 integration steps)


In [24]:
start = time.time()
trajs = await asyncio.gather(*(e.run_steps(nsteps) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 0.790020227432251 s


/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


In [25]:
cv = await descriptor_func_wrap(trajs[0])

In [26]:
cv

array([[ 2.4271595, -2.2134595],
       [ 2.5710735, -2.0945966]], dtype=float32)

In [27]:
trajs

[Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.part0002.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.part0002.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.part0002.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.part0002.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.tpr)]

In [28]:
for i, e in enumerate(engines):
    print(f"engine {i} did {e.frames_done} frames (== {e.steps_done} integration steps)")

engine 0 did 4643 frames (== 46430 integration steps)
engine 1 did 4683 frames (== 46830 integration steps)
engine 2 did 4659 frames (== 46590 integration steps)
engine 3 did 4667 frames (== 46670 integration steps)


In [29]:
start = time.time()
trajs = await asyncio.gather(*(e.run_steps(nsteps) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 0.7662858963012695 s


/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


In [30]:
cv = await descriptor_func_wrap(trajs[0])
print(cv)

[[ 2.5710735 -2.0945964]
 [ 2.3945775 -2.0325277]]


In [31]:
for i, e in enumerate(engines):
    print(f"engine {i} did {e.frames_done} frames (== {e.steps_done} integration steps)")

engine 0 did 4645 frames (== 46450 integration steps)
engine 1 did 4685 frames (== 46850 integration steps)
engine 2 did 4661 frames (== 46610 integration steps)
engine 3 did 4669 frames (== 46690 integration steps)


In [32]:
trajs

[Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.part0003.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.part0003.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.part0003.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.part0003.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.tpr)]

In [33]:
start = time.time()
trajs = await asyncio.gather(*(e.run_walltime(0.001) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


time elapsed: 4.720812082290649 s


In [34]:
cv = await descriptor_func_wrap(trajs[0])
print(cv)

[[ 2.3945775  -2.0325277 ]
 [ 2.3910885  -2.2671769 ]
 [ 2.3615117  -2.3732693 ]
 [ 2.4235663  -2.3129478 ]
 [ 2.5475566  -2.4553368 ]
 [ 2.567801   -2.400242  ]
 [ 2.5954676  -2.2265604 ]
 [ 2.623825   -2.2255142 ]
 [ 2.649412   -1.9096166 ]
 [ 2.468371   -1.8366671 ]
 [ 2.6026747  -1.7352847 ]
 [ 2.513448   -1.7282176 ]
 [ 2.5722501  -1.5727608 ]
 [ 2.5132236  -1.6647699 ]
 [ 2.671832   -1.444544  ]
 [ 2.5191677  -1.681522  ]
 [ 2.3569002  -1.5224135 ]
 [ 2.3022316  -1.5401325 ]
 [ 2.233673   -1.4627533 ]
 [ 2.1956456  -1.4051174 ]
 [ 2.1525352  -1.539607  ]
 [ 2.2531161  -1.6565682 ]
 [ 2.3814673  -1.6567446 ]
 [ 2.315785   -1.7186005 ]
 [ 2.5640042  -1.655767  ]
 [ 2.5357387  -1.5369643 ]
 [ 2.4836342  -1.4092546 ]
 [ 2.335542   -1.0997005 ]
 [ 2.3812332  -1.2199554 ]
 [ 2.3796494  -0.8874421 ]
 [ 2.4164553  -0.79592717]
 [ 2.555467   -0.7238861 ]
 [ 2.5956905  -0.8321967 ]
 [ 2.5072677  -0.66387117]
 [ 2.544372   -0.89377475]
 [ 2.5300014  -0.9704819 ]
 [ 2.5675106  -1.0239073 ]
 

In [35]:
for i, e in enumerate(engines):
    print(f"engine {i} did {e.frames_done} frames (== {e.steps_done} integration steps)")

engine 0 did 5124 frames (== 51240 integration steps)
engine 1 did 5164 frames (== 51640 integration steps)
engine 2 did 5148 frames (== 51480 integration steps)
engine 3 did 5140 frames (== 51400 integration steps)


In [36]:
trajs

[Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.part0004.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.part0004.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.part0004.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.part0004.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.tpr)]

In [37]:
start = time.time()
trajs = await asyncio.gather(*(e.run_walltime(0.001) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

cv = await descriptor_func_wrap(trajs[0])
print(cv)


/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


time elapsed: 4.883956432342529 s
[[ 2.6681943 -2.2446728]
 [ 2.6045394 -2.4662628]
 [ 2.873476  -2.324785 ]
 [ 2.8481727 -2.5032377]
 [ 2.8765519 -2.5411007]
 [ 2.7910988 -2.7878742]
 [ 2.8802383 -2.7731965]
 [ 2.6948845 -2.8651009]
 [ 2.472711  -2.8413522]
 [ 2.741218  -2.6945524]
 [ 2.549266  -2.7335606]
 [ 2.5383697 -2.4799852]
 [ 2.3854725 -2.4640412]
 [ 2.5161483 -2.4841807]
 [ 2.5390546 -2.4534662]
 [ 2.32028   -2.4504645]
 [ 2.3559737 -2.4193985]
 [ 2.333851  -2.4160051]
 [ 2.4338362 -2.475049 ]
 [ 2.1698303 -2.4636521]
 [ 2.383569  -2.5075831]
 [ 2.3505597 -2.5850449]
 [ 2.4076676 -2.4655786]
 [ 2.4298906 -2.517302 ]
 [ 2.3757548 -2.533818 ]
 [ 2.4757364 -2.4985774]
 [ 2.4180355 -2.5655484]
 [ 2.2659185 -2.6809478]
 [ 2.3155901 -2.5545135]
 [ 2.1110039 -2.6770852]
 [ 1.9676117 -2.6677158]
 [ 1.8957089 -2.7942305]
 [ 1.9024585 -2.7301328]
 [ 1.948929  -2.5294135]
 [ 2.0167813 -2.6652255]
 [ 2.0865476 -2.6814916]
 [ 2.0461433 -2.7087066]
 [ 2.2720623 -2.661086 ]
 [ 2.380312  -2.

In [39]:
trajs

[Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.part0005.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir0/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.part0005.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir1/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.part0005.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir2/blib.tpr),
 Trajectory(trajectory_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.part0005.trr, structure_file=/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/engine_wdir3/blib.tpr)]

In [34]:
start = time.time()
trajs = await asyncio.gather(*(e.run_steps(1) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 0.8452732563018799 s


/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


In [35]:
cv = await descriptor_func_wrap(trajs[0])
print(cv)

[[ 3.0745778 -2.777906 ]]


In [37]:
start = time.time()
trajs = await asyncio.gather(*(e.run_steps(1) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")
cv = await descriptor_func_wrap(trajs[0])
print(cv)

/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


OSError: XDR read error = integer

Exception ignored in: <function ReaderBase.__del__ at 0x7f0aefa608b0>
Traceback (most recent call last):
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py", line 2152, in __del__
    self.close()
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/XDR.py", line 179, in close
    self._xdr.close()
AttributeError: 'TRRReader' object has no attribute '_xdr'
Exception ignored in: <function ReaderBase.__del__ at 0x7f0aefa608b0>
Traceback (most recent call last):
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py", line 2152, in __del__
    self.close()
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/XDR.py", line 179, in close
    self._xdr.close()
AttributeError: 'TRRReader' object has no attribute '_xdr'
Exception ignored in: <function ReaderBase

In [38]:
start = time.time()
trajs = await asyncio.gather(*(e.run_steps(1) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")
cv = await descriptor_func_wrap(trajs[0])
print(cv)

/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


OSError: XDR read error = integer

Exception ignored in: <function ReaderBase.__del__ at 0x7f0aefa608b0>
Traceback (most recent call last):
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py", line 2152, in __del__
    self.close()
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/XDR.py", line 179, in close
    self._xdr.close()
AttributeError: 'TRRReader' object has no attribute '_xdr'
Exception ignored in: <function ReaderBase.__del__ at 0x7f0aefa608b0>
Traceback (most recent call last):
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py", line 2152, in __del__
    self.close()
  File "/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/coordinates/XDR.py", line 179, in close
    self._xdr.close()
AttributeError: 'TRRReader' object has no attribute '_xdr'
Exception ignored in: <function ReaderBase

In [36]:
for i, e in enumerate(engines):
    print(f"engine {i} did {e.frames_done} frames (== {e.steps_done} integration steps)")

engine 0 did 9222 frames (== 92220 integration steps)
engine 1 did 9206 frames (== 92060 integration steps)
engine 2 did 9006 frames (== 90060 integration steps)
engine 3 did 9046 frames (== 90460 integration steps)


In [29]:
start = time.time()
trajs = await asyncio.gather(*(e.run_walltime(0.01) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 36.5525848865509 s


/home/think/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


In [30]:
cv = await descriptor_func_wrap(trajs[0])
print(cv)

[[ 1.7949889 -2.3867085]
 [ 1.7086705 -2.3630643]
 [ 1.7360168 -2.3054514]
 ...
 [-1.4733312 -1.5860335]
 [-1.4640243 -1.643299 ]
 [-1.4391651 -1.8763256]]


In [31]:
for i, e in enumerate(engines):
    print(f"engine {i} did {e.frames_done} frames (== {e.steps_done} integration steps)")

engine 0 did 12460 frames (== 124600 integration steps)
engine 1 did 12700 frames (== 127000 integration steps)
engine 2 did 12494 frames (== 124940 integration steps)
engine 3 did 13316 frames (== 133160 integration steps)


In [32]:
start = time.time()
trajs = await asyncio.gather(*(e.run_walltime(0.01) for e in engines))
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 36.527894735336304 s


/home/think/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/MDAnalysis/topology/tpr/utils.py:389: DeprecationWarning: TPR files index residues from 0. From MDAnalysis version 2.0, resids will start at 1 instead. If you wish to keep indexing resids from 0, please set `tpr_resid_from_one=False` as a keyword argument when you create a new Topology or Universe.
  warnings.warn("TPR files index residues from 0. "


In [33]:
cv = await descriptor_func_wrap(trajs[0])
print(cv)

[[-1.4391651 -1.8763256]
 [-1.4037466 -1.9764206]
 [-1.4453897 -1.972756 ]
 ...
 [ 1.3600926 -2.4688985]
 [ 1.3947617 -2.3246064]
 [ 1.5066161 -2.267869 ]]


In [34]:
for i, e in enumerate(engines):
    print(f"engine {i} did {e.frames_done} frames (== {e.steps_done} integration steps)")

engine 0 did 16605 frames (== 166050 integration steps)
engine 1 did 16869 frames (== 168690 integration steps)
engine 2 did 16661 frames (== 166610 integration steps)
engine 3 did 17440 frames (== 174400 integration steps)


# propagator until state

In [13]:
import mdtraj as mdt
import numpy as np
"""
def psi(traj):
    traj = mdt.load(traj.trajectory_file, 
                    top=os.path.join(scratch_dir, "gmx_infiles/conf.gro"),  # mdt can not work with tprs, so we use theinitial gro for now
                    )
    psi = mdt.compute_psi(traj)
    return psi

def alpha_R(traj):
    traj = mdt.load(traj.trajectory_file, 
                    top=os.path.join(scratch_dir, "gmx_infiles/conf.gro"),  # mdt can not work with tprs, so we use theinitial gro for now
                    )
    psi = mdt.compute_dihedrals(traj, indices=[[6,8,14,16]])[:, 0]
    phi = mdt.compute_dihedrals(traj, indices=[[4,6,8,14]])[:, 0]
    state = np.full_like(psi, False, dtype=bool)
    # phi: -pi -> 0 
    # psi: > -50 but smaller 30 degree
    deg = 180/np.pi
    state[(phi <= 0) & (-50/deg <= psi) & (psi <= 30/deg)] = True
    return state

wrapped_alphaR = arcdd.trajectory.TrajectoryFunctionWrapper(alpha_R)
wrapped_psi = arcdd.trajectory.TrajectoryFunctionWrapper(psi)
"""

from state_funcs import alpha_R, C7_eq
wrapped_alphaR = aimmdd.TrajectoryFunctionWrapper(alpha_R, call_kwargs={"scratch_dir": scratch_dir})
wrapped_C7_eq = aimmdd.TrajectoryFunctionWrapper(C7_eq, call_kwargs={"scratch_dir": scratch_dir})

In [14]:
import aimmd.distributed.logic

In [15]:
propagators = [aimmd.distributed.logic.PropagatorUntilAnyState(states=[wrapped_alphaR, wrapped_C7_eq],
                                                               engine_cls=aimmdd.GmxEngine,
                                                               engine_kwargs={"gro_file":os.path.join(scratch_dir, "gmx_infiles/conf.gro"),
                                                                              "top_file":os.path.join(scratch_dir, "gmx_infiles/topol.top"),
                                                                               "mdrun_extra_args": "-nt 4",
                                                                              },
                                                               run_config=aimmdd.MDP(os.path.join(scratch_dir, "gmx_infiles/md.mdp")),
                                                               walltime_per_part=0.005,
                                                               
                                                              )
               for _ in range(n_engines)
               ]

Neither max_frames nor max_steps given. Setting max_frames to infinity.
Neither max_frames nor max_steps given. Setting max_frames to infinity.
Neither max_frames nor max_steps given. Setting max_frames to infinity.
Neither max_frames nor max_steps given. Setting max_frames to infinity.


In [17]:
#initial_tp_mdt = mdt.load(os.path.join(scratch_dir, "gmx_infiles/ala_400K_TP_low_barrier.h5"))

In [18]:
#initial_tp_mdt[10].save_trr(os.path.join(scratch_dir, "gmx_infiles/tp_frame.trr"))

In [16]:
starting_conf = aimmdd.Trajectory(trajectory_file=os.path.join(scratch_dir, "gmx_infiles/tp_frame.trr"),
                                  structure_file=os.path.join(scratch_dir, "gmx_infiles/tp_frame.gro"))

starting_conf = aimmdd.Trajectory(trajectory_file=os.path.join(scratch_dir, "gmx_infiles/conf.gro"),
                                  structure_file=os.path.join(scratch_dir, "gmx_infiles/conf.gro"))

In [17]:
wrapped_alphaR

TrajectoryFunctionWrapper(function=<function alpha_R at 0x7fe1fe04e700>, call_kwargs={'scratch_dir': '/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/'})

In [18]:
import mdtraj as mdt

In [19]:
mdt.load(os.path.join(scratch_dir, "gmx_infiles/conf.gro"), top=os.path.join(scratch_dir, "gmx_infiles/conf.gro"))

/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/mdtraj/formats/gro.py:307: UserWarning: WARNING: two consecutive residues with same number (ALA, ACE)
  warnings.warn("WARNING: two consecutive residues with same number (%s, %s)" % (thisresname, residue.name))
/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/mdtraj/formats/gro.py:307: UserWarning: WARNING: two consecutive residues with same number (NME, ALA)
  warnings.warn("WARNING: two consecutive residues with same number (%s, %s)" % (thisresname, residue.name))
/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/mdtraj/formats/gro.py:307: UserWarning: WARNING: two consecutive residues with same number (HOH, NME)
  warnings.warn("WARNING: two consecutive residues with same number (%s, %s)" % (thisresname, residue.name))
/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/mdtraj/core/trajectory.py:422: UserWarning: top= kwarg igno

<mdtraj.Trajectory with 1 frames, 1651 atoms, 546 residues, and unitcells at 0x7fe126c51d30>

In [20]:
mdt.load(starting_conf.trajectory_file, top=starting_conf.structure_file)

<mdtraj.Trajectory with 1 frames, 1651 atoms, 546 residues, and unitcells at 0x7fe126bff550>

In [21]:
alpha_R(starting_conf, **{"scratch_dir": scratch_dir})

/home/tb/hejung/.conda/envs/aimmd_nature_publish/lib/python3.8/site-packages/mdtraj/utils/validation.py:115: TypeCastPerformanceWarning: Casting unitcell_vectors dtype=float64 to <class 'numpy.float32'> 
  warnings.warn("Casting %s dtype=%s to %s " % (name, val.dtype, dtype),


array([ True])

In [22]:
await wrapped_alphaR(starting_conf)

array([ True])

In [23]:
scratch_dir

'/home/tb/hejung/DATA/aimmd_scratch/aimmd_distributed/'

In [24]:
tasks = [asyncio.create_task(p.propagate_and_concatenate(starting_configuration=starting_conf,
                                                         workdir=wdir,
                                                         deffnm="blib",
                                                         tra_out=os.path.join(wdir, "blub_until_state.trr"),
                                                          ))
         for p, wdir, mdp in zip(propagators, wdirs, mdps)]

done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)

In [25]:
list(done)[0]

<Task finished name='Task-5' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() got an unexpected keyword argument 'run_config'")>

In [26]:
tasks

[<Task finished name='Task-3' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() got an unexpected keyword argument 'run_config'")>,
 <Task finished name='Task-4' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() got an unexpected keyword argument 'run_config'")>,
 <Task finished name='Task-5' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() got an unexpected keyword argument 'run_config'")>,
 <Task finished name='Task-6' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() 

In [27]:
done, pending = await asyncio.wait(tasks,)# return_when=asyncio.FIRST_COMPLETED)

In [28]:
for i in done:
    print(i)
    print(tasks.index(i))

<Task finished name='Task-5' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() got an unexpected keyword argument 'run_config'")>
2
<Task finished name='Task-6' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() got an unexpected keyword argument 'run_config'")>
3
<Task finished name='Task-3' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() got an unexpected keyword argument 'run_config'")>
0
<Task finished name='Task-4' coro=<PropagatorUntilAnyState.propagate_and_concatenate() done, defined at /home/tb/hejung/Documents/sources/aimmd/aimmd/distributed/logic.py:1311> exception=TypeError("propagate() g

In [29]:
pending

set()

In [21]:
start = time.time()
result1 = await wrapped_func(trajs[-1])
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 0.48328495025634766 s


In [22]:
start = time.time()
results = await asyncio.gather(*(wrapped_func(t) for t in trajs))
end = time.time()
print(f"time elapsed: {end-start} s")

time elapsed: 0.5739212036132812 s


In [23]:
trajs

[Trajectory(trajectory_file=/home/think/scratch/arcd_distributed/engine_wdir0/blub.part0002.trr, topology_file=/home/think/scratch/arcd_distributed/engine_wdir0/blub.tpr),
 Trajectory(trajectory_file=/home/think/scratch/arcd_distributed/engine_wdir1/blub.part0002.trr, topology_file=/home/think/scratch/arcd_distributed/engine_wdir1/blub.tpr),
 Trajectory(trajectory_file=/home/think/scratch/arcd_distributed/engine_wdir2/blub.part0002.trr, topology_file=/home/think/scratch/arcd_distributed/engine_wdir2/blub.tpr),
 Trajectory(trajectory_file=/home/think/scratch/arcd_distributed/engine_wdir3/blub.part0002.trr, topology_file=/home/think/scratch/arcd_distributed/engine_wdir3/blub.tpr),
 Trajectory(trajectory_file=/home/think/scratch/arcd_distributed/engine_wdir4/blub.part0002.trr, topology_file=/home/think/scratch/arcd_distributed/engine_wdir4/blub.tpr),
 Trajectory(trajectory_file=/home/think/scratch/arcd_distributed/engine_wdir5/blub.part0002.trr, topology_file=/home/think/scratch/arcd_dist